### ISSUE TITLE
SSH config property doesn't allow custom path

### ISSUE THREAD

**Issue by GideonStowell** [basecamp/kamal-site#142]
Are the docs on the ssh/config property incorrect [here](https://kamal-deploy.org/docs/configuration/ssh/#config)? Specifically about if file paths are accepted.

Base on my usage the ssh/config property cannot accept a path. Only a boolean.

Related [issue](https://github.com/basecamp/kamal/issues/1161) in the kamal github repo.

**Comment by jeremy** [comment]
See #1129
