### ISSUE TITLE
--cpu-count is a Windows-only option

### ISSUE THREAD

**Issue by marckohlbrugge** [basecamp/kamal-site#49]
Kamal's docs mention a `--cpu-count` option here:

https://github.com/basecamp/kamal-site/blob/5901184cdb4e0f7b09e508b93e3ea65fc4de008f/_docs/configuration.md?plain=1#L327-L337

It took me a while to figure out why it didn't work for me. Turns out it's a Windows-only option:

> `--cpu-count			CPU count (Windows only)`

Source: https://docs.docker.com/engine/reference/commandline/container_run/#options

 I think we should suggest the more universal `--cpus` option instead:

> `-cpus		[API 1.25+](https://docker-docs.uclv.cu/engine/api/v1.25/) Number of CPUs`

---

I'm new to Docker. I could be wrong. I'm also not sure if Kamal uses API 1.25+.

**Comment by dhh** [comment]
Yes, please do add a PR for this.

**Comment by strzibny** [comment]
I believe this is already fixed in https://github.com/basecamp/kamal-site/pull/46 and can be closed.
