### ISSUE TITLE
Add full example deployment to docs site

### ISSUE THREAD

**Issue by ad8lmondy** [basecamp/kamal-site#50]
Hello,

I came across Kamal, and happily browsed the website - but I could not find a full example deployment to tie all the configuration bits together.

Could you add an example deployment, or alternately, a single config file enumerating all the configs, as a reference?

Thanks!

**Comment by ad8lmondy** [comment]
Looks like https://github.com/basecamp/kamal-site/pull/43 is relatively similar to this request.

**Comment by dhh** [comment]
Video is an end-to-end example. But yeah, would be nice to have even more.
