### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by iennae** [basecamp/kamal-site#57]
I found this project via this post https://dev.to/hsatac/kamal-deploy-on-gcp-18jn on dev.to but as I started looking around I realized that there is no obvious license file. It'd be helpful to know the explicit license for this project. Thanks!

**Comment by nickhammond** [comment]
Hey @iennae,

This repository is just for the Kamal website, the Kamal project has an MIT license which is here: https://github.com/basecamp/kamal/blob/main/MIT-LICENSE
