### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by nickhammond** [basecamp/kamal-site#72]
The documentation pages are on individual pages now which is great because we can link directly to them from Discord/GitHub but it's harder to find specific sections within the docs. Here's an example from Discord:

> I moved the config folder to the root. Now how do I specify the path to the Dockerfile? **I remember there was such a setting, but I can't find it in the documentation**

Could we use something like lunr.js? Happy to start a PR for this but just wanted to check in first. 

- How to: https://www.stephanmiller.com/static-site-search/
- lunr.js site: https://lunrjs.com/

**Comment by djmb** [comment]
Hi @nickhammond!

Yes that sounds great, let's give it a go!

**Comment by nickhammond** [comment]
Hey @djmb,

Built this out a bit this morning, had a couple of comments and wanted to see if you had a preference:

1. Search field placement - Right now it's at the top of the aside which is useful if you're linked to an expanded subsection but I could also see it being at the bottom of the aside.
2. Search button - Thinking about just swapping this with a magnifying glass emoji but can also just keep it as is.
3. The grey-colored test below the search result link is the docs section it's in, thought this might be helpful but I can easily remove it.

<img width="1248" alt="image" src="https://github.com/basecamp/kamal-site/assets/17698/af7de4b1-55c0-4c52-874e-4e108bc7898d">

**Comment by djmb** [comment]
Thanks @nickhammond! Sorry for the delay here, I've been away for the last couple of weeks.

@seanmitchell - could I get your thoughts here? 🙏

**Comment by seanmitchell** [comment]
Hey @nickhammond, this sounds great!

I started a PR here https://github.com/basecamp/kamal-site/pull/90 that adds styling for the search field in the docs layout and nav.

I like the placement of the search field up top. And using a little icon for the button. The search results layout looks good — want to get it all wired up in [this PR](https://github.com/basecamp/kamal-site/pull/90)?

**Comment by nickhammond** [comment]
@djmb No worries, same here! Just finished up getting married last week 🎉

@seanmitchell This looks great, thanks for the CSS help. I'll get this mapped to everything I have running locally and pushed up to that PR.
