### ISSUE TITLE
The documentation has become harder to navigate

### ISSUE THREAD

**Issue by n4cr** [basecamp/kamal-site#86]
Hey team,

Thanks for building Kamal. It is a great product and I use it heavily.

I've been trying to find items in the documentation and I believe new changes has made the navigation in the documentation harder. Before, there were long pages of documentation where searching in the page would quickly bring you to topic you were looking for. Now, many topics do not have text and only link to external pages.

For example I was looking for `cron` to figure out how to add cron to my `deploy.yml` but it has either disappeared or I can't find it and there's no Search either.

Thanks

**Comment by djmb** [comment]
Thanks @n4cr! I've added the cron docs back in, they shouldn't have been removed.

> Now, many topics do not have text and only link to external pages.

Do you have any other examples of this I could take a look at?

Regarding search, @nickhammond is looking at adding that (see https://github.com/basecamp/kamal-site/issues/72), so hopefully that should alleviate some of your issues here.
