### ISSUE TITLE
UI Navigation issue: 'Builder examples' sidebar link doesn't work

### ISSUE THREAD

**Issue by abratashov** [basecamp/kamal-site#93]
When following the 'Builder examples' sidebar link it refers to the 'Builder' page https://kamal-deploy.org/docs/configuration/builders

Also, these two items have a bold style. Only the direct link works fine https://kamal-deploy.org/docs/configuration/builder-examples

![2024-07-27_12-25](https://github.com/user-attachments/assets/4dd630be-39ad-473d-9521-cb60462930d7)

**Comment by seanmitchell** [comment]
Hey @abratashov, thank you for the heads up — this has been fixed. 🤝
