### ISSUE TITLE
Website Targets Kamal 1.8.3, But Docker Alias Defaults to Latest Tag (v2.0.0.rc1)

### ISSUE THREAD

**Issue by marcpicaud** [basecamp/kamal-site#99]
Hi,

The following problem made me super confused so I thought I'd raise the issue to you guys.

Currently, the [Kamal website](https://kamal-deploy.org) targets Kamal 1.8.3.

But the Docker alias for macOS or Linux user uses the `latest` tag which resolves to v2.0.0.rc1

<img width="2151" alt="image" src="https://github.com/user-attachments/assets/2608b929-8c19-4e0c-9417-8771b8adc44f">

**Comment by dhh** [comment]
Yeah, need to not have beta releases tagged as latest. But at least now 2.0 final is out.
